#!/usr/bin/env bash

now_playing() {
    status=$(playerctl status)

    if [ "$status" == "" ]; then
        return
    fi

    artist=$(playerctl metadata xesam:artist)
    title=$(playerctl metadata xesam:title)

    if [ "$status" == "Playing" ]; then
        echo "$artist — $title"
    elif [ "$status" == "Paused" ]; then
        echo "▐▐ $artist — $title"
    else
        echo "$status"
    fi
}

now_playing

