#!/usr/bin/env bash

now_playing() {
    status=$(playerctl status --player=spotify)

    if [ "$status" == "" ]; then
        return
    fi

    title=$(playerctl --player=spotify metadata xesam:title)
    artist=$(playerctl --player=spotify metadata xesam:artist)

    if [ "$status" == "Playing" ]; then
        # ▷
        echo "🎵$artist — $title"
    elif [ "$status" == "Paused" ]; then
        echo "▐▐ $artist — $title"
    else
        echo "$status"
    fi
}

now_playing
